# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_TOGGLE)	+= switch_toggle.o
obj-$(CONFIG_SWITCH_FSA9480)	+= fsa9480.o
obj-$(CONFIG_SWITCH_QSS_BOOTPARAM)	+= qss_bootparam.o
